{
 "title": "Latencia por endpoint",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Todas requisições por minuto",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[$__rate_interval])*60"
    }
   ]
  },
  {
   "title": "Contagem de requisições por rotas",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint, method) (increase(http_requests_received_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contagem de Requisições por Status de Resposta",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total[$__range])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória total em bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "dotnet_total_memory_bytes" }
   ]
  },
  {
   "title": "Latência por Endpoint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência das Requisições",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum[5m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Recursos da CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}